import time
import random
print("Hello. Welcome to best PC software recommendations.")
flag = True
while flag:
    print('Please Chose one of the listed categories : ')
    print('1.Media Player')
    print('2.Photo Editor')
    print('3.Video Editor')
    print('4.File Compressor')
    print('5.Antivrus')
    print('6.Utility')
    print('7.Documentation')
    print('8.VPN')
    print('9.Cloud Storage')
    print('10.Browser')
    print('0. EXIT')
    choice = int(input('Enter your choice: '))
    if choice == 1:
        print()
        print()
        print('1.VLC')
        print('2.Media Player Classic')
        print('3.Kodi')
        print()
        print()
        time.sleep(4)
    elif choice == 2:
        print()
        print()
        print("1.Adobe PhotoShop (Paid)")
        print('2.Gimp')
        print('3.PhotoScape')
        print()
        print()
        time.sleep(4)
    elif choice == 3:
        print()
        print()
        print('1.Davinci Resolve')
        print('2.CapCut')
        print('3.Shotcut')
        print()
        time.sleep(4)
    elif choice == 4:
        print()
        print()
        print('1. 7Zip')
        print('2.WinRAR')
        print()
        print()
        time.sleep(4)
    elif choice == 5:
        print()
        print()
        print('1.Bitdefender(Paid)')
        print('2.Kaspersky(Paid)')
        print('3.MalwareBytes')
        print()
        print()
        time.sleep(4)
    elif choice == 6:
        print()
        print()
        print('1.Everything')
        print('2.WizTree')
        print('3.Notepad++')
        print('4.ArcSoft WebCam')
        print('5.Bandicam')
        print('6.Bijoy')
        print('7.Avro')
        print('8.VS Code')
        print('9.Intel Driver and Support')
        print('10.FxSound')
        print('11.IO Bit unlocker')
        print()
        time.sleep(15)
    elif choice == 7:
        print()
        print()
        print('1.Microsoft Office')
        print('2.OpenOffice')
        print('3.Libre Office')
        print()
        print()
        time.sleep(4)
    elif choice == 8:
        print()
        print()
        print('1.Proton')
        print('2.Turbo')
        print()
        print()
        time.sleep(4)
    elif choice == 9:
        print()
        print()
        print('1.Mega')
        print('2.Google Drive')
        print('3.Dropbox')
        print()
        print()
        time.sleep(4)
    elif choice == 10:
        print()
        print()
        print('FireFox')
        print('Brave')
        print('Chrome')
        time.sleep(4)
    else:
        print('Thanks for using my program')
        break